### ISSUE TITLE
Extend the Manifest file to include application Meta Data

### ISSUE THREAD

**Issue by lock9** [simplitech/neo#4]
- [ ] Add script header to ensure the VM can run scripts using multiple script versions
- [ ] Add manifest version,  VM version/magic (discuss)
- [ ] Migrate contract name, contact, etc. to the application manifest
- [ ] Add inheritance migration restriction (can or cannot update parent script)
- [ ] Add safe methods (stateless methods)
- [ ] Add witnesses 'protected' methods (methods that don't need witnesses check)
- [ ] DevPack: Update to support new manifest format
